# Generated by Django 4.2.2 on 2023-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone', models.TextField()),
                ('mail', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=15)),
                ('materials', models.CharField(max_length=15)),
            ],
        ),
    ]
